# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 007963f63561aed7900561ed3035b7cb069047d2bd6c3fe7da3d3954146dcee21d50ebdca7255399ca8f059b8fb10c95c8f073e5dadf2224dbbaab7448125dc4

test:
  secret_key_base: adcbe7d6a88050ea7b249ef3f8b43d025da567292ec7da0fac860cea3b7b5c3a57ca45a2dd11a445f9bbd537e7d42eb9ed8e88907ec5107f2c3b618ac3cb01a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
